export function getImages() {
  return images;
}

const images = [
  {
    title: "autumn sunrise.webp",
    fullRes: "../paintings/autumn-sunrise.webp",
    lowRes: "../paintings/low-res/autumn-sunrise.webp",
    height: 713,
    width: 960,
    id: 0,
  },
  {
    title: "bern.webp",
    fullRes: "../paintings/bern.webp",
    lowRes: "../paintings/low-res/bern.webp",
    height: 482,
    width: 960,
    id: 1,
  },
  {
    title: "bologna.webp",
    fullRes: "../paintings/bologna.webp",
    lowRes: "../paintings/low-res/bologna.webp",
    height: 634,
    width: 960,
    id: 2,
  },
  {
    title: "breslau.webp",
    fullRes: "../paintings/breslau.webp",
    lowRes: "../paintings/low-res/breslau.webp",
    height: 776,
    width: 960,
    id: 3,
  },
  {
    title: "center of the earth.webp",
    fullRes: "../paintings/center-of-the-earth.webp",
    lowRes: "../paintings/low-res/center-of-the-earth.webp",
    height: 960,
    width: 960,
    id: 4,
  },
  {
    title: "cinque terre.webp",
    fullRes: "../paintings/cinque-terre.webp",
    lowRes: "../paintings/low-res/cinque-terre.webp",
    height: 1441,
    width: 960,
    id: 5,
  },
  {
    title: "copper.webp",
    fullRes: "../paintings/copper.webp",
    lowRes: "../paintings/low-res/copper.webp",
    height: 751,
    width: 960,
    id: 6,
  },
  {
    title: "early spring.webp",
    fullRes: "../paintings/early-spring.webp",
    lowRes: "../paintings/low-res/early-spring.webp",
    height: 784,
    width: 960,
    id: 7,
  },
  {
    title: "enough is enough.webp",
    fullRes: "../paintings/enough-is-enough.webp",
    lowRes: "../paintings/low-res/enough-is-enough.webp",
    height: 796,
    width: 960,
    id: 8,
  },
  {
    title: "forest.webp",
    fullRes: "../paintings/forest.webp",
    lowRes: "../paintings/low-res/forest.webp",
    height: 552,
    width: 960,
    id: 9,
  },
  {
    title: "golden landscape.webp",
    fullRes: "../paintings/golden-landscape.webp",
    lowRes: "../paintings/low-res/golden-landscape.webp",
    height: 488,
    width: 960,
    id: 10,
  },
  {
    title: "good as hell.webp",
    fullRes: "../paintings/good-as-hell.webp",
    lowRes: "../paintings/low-res/good-as-hell.webp",
    height: 335,
    width: 960,
    id: 11,
  },
  {
    title: "grue and bleen.webp",
    fullRes: "../paintings/grue-and-bleen.webp",
    lowRes: "../paintings/low-res/grue-and-bleen.webp",
    height: 314,
    width: 960,
    id: 12,
  },
  {
    title: "honey field.webp",
    fullRes: "../paintings/honey-field.webp",
    lowRes: "../paintings/low-res/honey-field.webp",
    height: 660,
    width: 960,
    id: 13,
  },
  {
    title: "infra black.webp",
    fullRes: "../paintings/infra-black.webp",
    lowRes: "../paintings/low-res/infra-black.webp",
    height: 482,
    width: 960,
    id: 14,
  },
  {
    title: "infra white.webp",
    fullRes: "../paintings/infra-white.webp",
    lowRes: "../paintings/low-res/infra-white.webp",
    height: 326,
    width: 960,
    id: 15,
  },
  {
    title: "living coral.webp",
    fullRes: "../paintings/living-coral.webp",
    lowRes: "../paintings/low-res/living-coral.webp",
    height: 324,
    width: 960,
    id: 16,
  },
  {
    title: "lonely island.webp",
    fullRes: "../paintings/lonely-island.webp",
    lowRes: "../paintings/low-res/lonely-island.webp",
    height: 768,
    width: 960,
    id: 17,
  },
  {
    title: "look up for answers.webp",
    fullRes: "../paintings/look-up-for-answers.webp",
    lowRes: "../paintings/low-res/look-up-for-answers.webp",
    height: 545,
    width: 960,
    id: 18,
  },
  {
    title: "melting landscapes.webp",
    fullRes: "../paintings/melting-landscapes.webp",
    lowRes: "../paintings/low-res/melting-landscapes.webp",
    height: 788,
    width: 960,
    id: 19,
  },
  {
    title: "murmuration.webp",
    fullRes: "../paintings/murmuration.webp",
    lowRes: "../paintings/low-res/murmuration.webp",
    height: 301,
    width: 960,
    id: 20,
  },
  {
    title: "out of the blue.webp",
    fullRes: "../paintings/out-of-the-blue.webp",
    lowRes: "../paintings/low-res/out-of-the-blue.webp",
    height: 791,
    width: 960,
    id: 21,
  },
  {
    title: "pearly sky.webp",
    fullRes: "../paintings/pearly-sky.webp",
    lowRes: "../paintings/low-res/pearly-sky.webp",
    height: 960,
    width: 960,
    id: 22,
  },
  {
    title: "pink sky.webp",
    fullRes: "../paintings/pink-sky.webp",
    lowRes: "../paintings/low-res/pink-sky.webp",
    height: 482,
    width: 960,
    id: 23,
  },
  {
    title: "poppies field.webp",
    fullRes: "../paintings/poppies-field.webp",
    lowRes: "../paintings/low-res/poppies-field.webp",
    height: 321,
    width: 960,
    id: 24,
  },
  {
    title: "second skin.webp",
    fullRes: "../paintings/second-skin.webp",
    lowRes: "../paintings/low-res/second-skin.webp",
    height: 1090,
    width: 960,
    id: 25,
  },
  {
    title: "space.webp",
    fullRes: "../paintings/space.webp",
    lowRes: "../paintings/low-res/space.webp",
    height: 804,
    width: 960,
    id: 26,
  },
  {
    title: "sparkling lake.webp",
    fullRes: "../paintings/sparkling-lake.webp",
    lowRes: "../paintings/low-res/sparkling-lake.webp",
    height: 398,
    width: 960,
    id: 27,
  },
  {
    title: "spectrum of thoughts.webp",
    fullRes: "../paintings/spectrum-of-thoughts.webp",
    lowRes: "../paintings/low-res/spectrum-of-thoughts.webp",
    height: 960,
    width: 960,
    id: 28,
  },
  {
    title: "subdominant.webp",
    fullRes: "../paintings/subdominant.webp",
    lowRes: "../paintings/low-res/subdominant.webp",
    height: 616,
    width: 960,
    id: 29,
  },
  {
    title: "vespera and prima.webp",
    fullRes: "../paintings/vespera-and-prima.webp",
    lowRes: "../paintings/low-res/vespera-and-prima.webp",
    height: 333,
    width: 960,
    id: 30,
  },
  {
    title: "vilnus.webp",
    fullRes: "../paintings/vilnus.webp",
    lowRes: "../paintings/low-res/vilnus.webp",
    height: 621,
    width: 960,
    id: 31,
  },
  {
    title: "water landscape.webp",
    fullRes: "../paintings/water-landscape.webp",
    lowRes: "../paintings/low-res/water-landscape.webp",
    height: 327,
    width: 960,
    id: 32,
  },
  {
    title: "water lilies.webp",
    fullRes: "../paintings/water-lilies.webp",
    lowRes: "../paintings/low-res/water-lilies.webp",
    height: 742,
    width: 960,
    id: 33,
  },
  {
    title: "widawa river.webp",
    fullRes: "../paintings/widawa-river.webp",
    lowRes: "../paintings/low-res/widawa-river.webp",
    height: 776,
    width: 960,
    id: 34,
  },
  {
    title: "world united.webp",
    fullRes: "../paintings/world-united.webp",
    lowRes: "../paintings/low-res/world-united.webp",
    height: 960,
    width: 960,
    id: 35,
  },
];
