export function getImages() {
  return images;
}

const images = [
  {
    title: "autumn sunrise",
    fullRes: "../paintings/autumn-sunrise.webp",
    fileName: "autumn-sunrise.webp",
    height: 713,
    width: 960,
    heightCm: 60,
    widthCm: 80,
    id: 0,
  },
  {
    title: "bern",
    fullRes: "../paintings/bern.webp",
    fileName: "bern.webp",
    height: 482,
    width: 960,
    heightCm: 80,
    widthCm: 240,
    id: 1,
  },
  {
    title: "bologna",
    fullRes: "../paintings/bologna.webp",
    fileName: "bologna.webp",
    height: 634,
    width: 960,
    heightCm: 80,
    widthCm: 120,
    id: 2,
  },
  {
    title: "breslau",
    fullRes: "../paintings/breslau.webp",
    fileName: "breslau.webp",
    height: 776,
    width: 960,
    heightCm: 100,
    widthCm: 80,
    id: 3,
  },
  {
    title: "center of the earth",
    fullRes: "../paintings/center-of-the-earth.webp",
    fileName: "center-of-the-earth.webp",
    height: 960,
    width: 960,
    heightCm: 120,
    widthCm: 120,
    id: 4,
  },
  {
    title: "cinque terre",
    fullRes: "../paintings/cinque-terre.webp",
    fileName: "cinque-terre.webp",
    height: 1441,
    width: 960,
    heightCm: 120,
    widthCm: 80,
    id: 5,
  },
  {
    title: "copper",
    fullRes: "../paintings/copper.webp",
    fileName: "copper.webp",
    height: 751,
    width: 960,
    heightCm: 30,
    widthCm: 40,
    id: 6,
  },
  {
    title: "early spring",
    fullRes: "../paintings/early-spring.webp",
    fileName: "early-spring.webp",
    height: 784,
    width: 960,
    heightCm: 50,
    widthCm: 60,
    id: 7,
  },
  {
    title: "enough is enough",
    fullRes: "../paintings/enough-is-enough.webp",
    fileName: "enough-is-enough.webp",
    height: 796,
    width: 960,
    heightCm: 50,
    widthCm: 60,
    id: 8,
  },
  {
    title: "forest",
    fullRes: "../paintings/forest.webp",
    fileName: "forest.webp",
    height: 552,
    width: 960,
    heightCm: 80,
    widthCm: 120,
    id: 9,
  },
  {
    title: "golden landscape",
    fullRes: "../paintings/golden-landscape.webp",
    fileName: "golden-landscape.webp",
    height: 488,
    width: 960,
    heightCm: 70,
    widthCm: 120,
    id: 10,
  },
  {
    title: "good as hell",
    fullRes: "../paintings/good-as-hell.webp",
    fileName: "good-as-hell.webp",
    height: 335,
    width: 960,
    heightCm: 60,
    widthCm: 200,
    id: 11,
  },
  {
    title: "grue and bleen",
    fullRes: "../paintings/grue-and-bleen.webp",
    fileName: "grue-and-bleen.webp",
    height: 314,
    width: 960,
    heightCm: 80,
    widthCm: 240,
    id: 12,
  },
  {
    title: "honey field",
    fullRes: "../paintings/honey-field.webp",
    fileName: "honey-field.webp",
    height: 660,
    width: 960,
    heightCm: 70,
    widthCm: 100,
    id: 13,
  },
  {
    title: "infra black",
    fullRes: "../paintings/infra-black.webp",
    fileName: "infra-black.webp",
    height: 482,
    width: 960,
    heightCm: 80,
    widthCm: 120,
    id: 14,
  },
  {
    title: "infra white",
    fullRes: "../paintings/infra-white.webp",
    fileName: "infra-white.webp",
    height: 326,
    width: 960,
    heightCm: 80,
    widthCm: 240,
    id: 15,
  },
  {
    title: "living coral",
    fullRes: "../paintings/living-coral.webp",
    fileName: "living-coral.webp",
    height: 324,
    width: 960,
    heightCm: 80,
    widthCm: 240,
    id: 16,
  },
  {
    title: "lonely island",
    fullRes: "../paintings/lonely-island.webp",
    fileName: "lonely-island.webp",
    height: 768,
    width: 960,
    heightCm: 30,
    widthCm: 40,
    id: 17,
  },
  {
    title: "look up for answers",
    fullRes: "../paintings/look-up-for-answers.webp",
    fileName: "look-up-for-answers.webp",
    height: 545,
    width: 960,
    heightCm: 70,
    widthCm: 120,
    id: 18,
  },
  {
    title: "melting landscapes",
    fullRes: "../paintings/melting-landscapes.webp",
    fileName: "melting-landscapes.webp",
    height: 788,
    width: 960,
    heightCm: 30,
    widthCm: 40,
    id: 19,
  },
  {
    title: "murmuration",
    fullRes: "../paintings/murmuration.webp",
    fileName: "murmuration.webp",
    height: 301,
    width: 960,
    heightCm: 80,
    widthCm: 240,
    id: 20,
  },
  {
    title: "out of the blue",
    fullRes: "../paintings/out-of-the-blue.webp",
    fileName: "out-of-the-blue.webp",
    height: 791,
    width: 960,
    heightCm: 50,
    widthCm: 60,
    id: 21,
  },
  {
    title: "pearly sky",
    fullRes: "../paintings/pearly-sky.webp",
    fileName: "pearly-sky.webp",
    height: 960,
    width: 960,
    heightCm: 100,
    widthCm: 100,
    id: 22,
  },
  {
    title: "pink sky",
    fullRes: "../paintings/pink-sky.webp",
    fileName: "pink-sky.webp",
    height: 482,
    width: 960,
    heightCm: 60,
    widthCm: 120,
    id: 23,
  },
  {
    title: "poppies field",
    fullRes: "../paintings/poppies-field.webp",
    fileName: "poppies-field.webp",
    height: 321,
    width: 960,
    heightCm: 80,
    widthCm: 240,
    id: 24,
  },
  {
    title: "second skin",
    fullRes: "../paintings/second-skin.webp",
    fileName: "second-skin.webp",
    height: 1090,
    width: 960,
    heightCm: 120,
    widthCm: 100,
    id: 25,
  },
  {
    title: "space",
    fullRes: "../paintings/space.webp",
    fileName: "space.webp",
    height: 804,
    width: 960,
    heightCm: 100,
    widthCm: 120,
    id: 26,
  },
  {
    title: "sparkling lake",
    fullRes: "../paintings/sparkling-lake.webp",
    fileName: "sparkling-lake.webp",
    height: 398,
    width: 960,
    heightCm: "N/A",
    widthCm: "N/A",
    id: 27,
  },
  {
    title: "spectrum of thoughts",
    fullRes: "../paintings/spectrum-of-thoughts.webp",
    fileName: "spectrum-of-thoughts.webp",
    height: 960,
    width: 960,
    heightCm: 120,
    widthCm: 100,
    id: 28,
  },
  {
    title: "subdominant",
    fullRes: "../paintings/subdominant.webp",
    fileName: "subdominant.webp",
    height: 616,
    width: 960,
    heightCm: 40,
    widthCm: 60,
    id: 29,
  },
  {
    title: "vespera and prima",
    fullRes: "../paintings/vespera-and-prima.webp",
    fileName: "vespera-and-prima.webp",
    height: 333,
    width: 960,
    heightCm: 60,
    widthCm: 170,
    id: 30,
  },
  {
    title: "vilnus",
    fullRes: "../paintings/vilnus.webp",
    fileName: "vilnus.webp",
    height: 621,
    width: 960,
    heightCm: 80,
    widthCm: 100,
    id: 31,
  },
  {
    title: "water landscape",
    fullRes: "../paintings/water-landscape.webp",
    fileName: "water-landscape.webp",
    height: 327,
    width: 960,
    heightCm: 20,
    widthCm: 70,
    id: 32,
  },
  {
    title: "water lilies",
    fullRes: "../paintings/water-lilies.webp",
    fileName: "water-lilies.webp",
    height: 742,
    width: 960,
    heightCm: "N/A",
    widthCm: "N/A",
    id: 33,
  },
  {
    title: "widawa river",
    fullRes: "../paintings/widawa-river.webp",
    fileName: "widawa-river.webp",
    height: 776,
    width: 960,
    heightCm: 80,
    widthCm: 120,
    id: 34,
  },
  {
    title: "world united",
    fullRes: "../paintings/world-united.webp",
    fileName: "world-united.webp",
    height: 960,
    width: 960,
    heightCm: 70,
    widthCm: 70,
    id: 35,
  },
];
